### ISSUE TITLE
No longer working with Hotgrid

### ISSUE THREAD

**Issue by fosterc1** [cgkineo/adapt-graphicLottie#13]
This previously used to working with Hotgrid: https://github.com/cgkineo/adapt-hotgrid and although the svgz are being displayed on the initial hotgrid, when you select the hotgrid item the notify popup no longer shows and locks up the page.

### Your environment
* version (AT v5.29.3/Framework v011.1)
* which browser and its version - all browsers
* device(s) + operating system(s) - all devices

### Steps to reproduce
Tell us how to reproduce this issue.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

**Comment by kirsty-hames** [comment]
I can replicate the issue described for both Hotgrid and Hotgraphic. No console errors to report.

Using svgz in question feedback however works as expected so I don't think this issue is global to Notify. Both Hotgrid and Hotgraphic have their own popup template so the issue might be specific to this.

**Comment by oliverfoster** [comment]
Can you try with the latest version please?

**Comment by fosterc1** [comment]
Hello

I've tested v2.0.2 of the plugin and still getting the same results. The svgz works fine when used as the item graphic, however if an svgz is used as the popup graphic when the item graphic is selected the browser locks up.

AT: v0.11.1 / FW: v5.31.23

Hope this helps

**Comment by oliverfoster** [comment]
please give the latest version a go
